/**
 * Section Content Schema — the AI ↔ frontend contract.
 *
 * The AI generates STRUCTURED CONTENT (pure data) per section type.
 * The frontend maps (type + variant) → a hand-designed component that
 * renders `content` + `theme`. No HTML is ever generated by the AI.
 *
 * Every section type has:
 *   - a set of allowed `variant` strings (which designed component to use)
 *   - a `content` object with a fixed, typed shape
 *
 * This is the single source of truth for both the AI prompt (what to emit)
 * and the frontend renderer (what to expect).
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Theme — global visual tokens chosen by the AI from the design guide.
// Expanded from 8 color-only tokens to 14 tokens covering color, typography,
// spacing, depth, and decoration. This gives the AI ~15× more expressiveness
// without changing the component code.
// ---------------------------------------------------------------------------

export const ThemeSchema = z.object({
  // -- Color (8) --
  accent: z.string(),        // primary brand/action color (hex)
  bg: z.string(),            // page canvas
  cardBg: z.string(),        // card surface
  text: z.string(),          // primary text
  textSecondary: z.string(), // muted text
  ctaText: z.string(),       // text on accent-colored surfaces
  borderRadius: z.string(),  // e.g. "12px"
  buttonRadius: z.string(),  // e.g. "9999px"

  // -- Typography (1) --
  fontStyle: z.enum(["sans-clean", "serif-classic", "mono-tech", "mixed-warm"]),

  // -- Rhythm (1) --
  spacing: z.enum(["compact", "comfortable", "spacious"]),

  // -- Depth (1) --
  elevation: z.enum(["flat", "subtle-shadow", "soft-glow"]),

  // -- Decoration (1) --
  decorDensity: z.enum(["minimal", "moderate", "rich"]),

  // -- Master style switch (1) — sets the overall mood; cascades into the
  //    sections' typography, spacing, and decoration choices.
  layoutStyle: z.enum(["editorial", "startup", "boutique"]),
});
export type Theme = z.infer<typeof ThemeSchema>;

// ---------------------------------------------------------------------------
// LayoutStyle → sensible defaults (used by the prompt to explain to the AI
// what each style means, and by the frontend as fallback).
// ---------------------------------------------------------------------------

export const LAYOUT_STYLE_GUIDE: Record<string, {
  fontStyle: string;
  spacing: string;
  elevation: string;
  decorDensity: string;
  vibe: string;
}> = {
  editorial: {
    fontStyle: "serif-classic",
    spacing: "spacious",
    elevation: "flat",
    decorDensity: "minimal",
    vibe: "warm paper, serif headlines, narrow columns, hairline rules, ink-on-page — like a printed magazine or literary journal",
  },
  startup: {
    fontStyle: "sans-clean",
    spacing: "comfortable",
    elevation: "subtle-shadow",
    decorDensity: "moderate",
    vibe: "crisp sans, generous whitespace, soft card shadows, bold CTAs, clean grids — like a modern SaaS landing page",
  },
  boutique: {
    fontStyle: "mixed-warm",
    spacing: "comfortable",
    elevation: "soft-glow",
    decorDensity: "rich",
    vibe: "serif headlines + sans body, tinted accent panels, glowing CTAs, pill badges, soft decorative texture — like an artisan shop or premium brand",
  },
};

// ---------------------------------------------------------------------------
// Per-section content shapes
// ---------------------------------------------------------------------------

export const HeroContent = z.object({
  eyebrow: z.string().optional(),
  title: z.string(),
  subtitle: z.string(),
  ctaText: z.string(),
  imageUrl: z.string().optional(),
});
export type HeroContent = z.infer<typeof HeroContent>;

export const AboutContent = z.object({
  eyebrow: z.string().optional(),
  heading: z.string(),
  body: z.string(),
  imageUrl: z.string().optional(),
  stats: z.array(z.object({ value: z.string(), label: z.string() })).optional(),
});
export type AboutContent = z.infer<typeof AboutContent>;

export const ProductGridContent = z.object({
  eyebrow: z.string().optional(),
  heading: z.string(),
});
export type ProductGridContent = z.infer<typeof ProductGridContent>;

export const TestimonialContent = z.object({
  eyebrow: z.string().optional(),
  heading: z.string(),
  items: z.array(
    z.object({
      quote: z.string(),
      name: z.string(),
      role: z.string().optional(),
    })
  ),
});
export type TestimonialContent = z.infer<typeof TestimonialContent>;

export const CtaContent = z.object({
  heading: z.string(),
  subtitle: z.string().optional(),
  ctaText: z.string(),
});
export type CtaContent = z.infer<typeof CtaContent>;

export const ContactContent = z.object({
  eyebrow: z.string().optional(),
  heading: z.string(),
  whatsapp: z.string().optional(),
  address: z.string().optional(),
  email: z.string().optional(),
  hours: z.string().optional(),
});
export type ContactContent = z.infer<typeof ContactContent>;

export const FaqContent = z.object({
  eyebrow: z.string().optional(),
  heading: z.string(),
  items: z.array(z.object({ question: z.string(), answer: z.string() })),
});
export type FaqContent = z.infer<typeof FaqContent>;

// ---------------------------------------------------------------------------
// Section registry: type → allowed variants + content schema
// ---------------------------------------------------------------------------

export const SECTION_DEFINITIONS = {
  hero: {
    variants: ["split", "centered", "image-bg"] as const,
    content: HeroContent,
  },
  about: {
    variants: ["split", "centered", "stats"] as const,
    content: AboutContent,
  },
  "product-grid": {
    variants: ["grid", "list"] as const,
    content: ProductGridContent,
  },
  testimonial: {
    variants: ["cards", "single"] as const,
    content: TestimonialContent,
  },
  cta: {
    variants: ["band", "card"] as const,
    content: CtaContent,
  },
  contact: {
    variants: ["split", "centered"] as const,
    content: ContactContent,
  },
  faq: {
    variants: ["accordion", "grid"] as const,
    content: FaqContent,
  },
} as const;

export type SectionKind = keyof typeof SECTION_DEFINITIONS;
export type VariantOf<K extends SectionKind> =
  (typeof SECTION_DEFINITIONS)[K]["variants"][number];

// ---------------------------------------------------------------------------
// A generated section (AI output unit)
// ---------------------------------------------------------------------------

export const GeneratedSectionSchema = z.object({
  type: z.enum([
    "hero",
    "about",
    "product-grid",
    "testimonial",
    "cta",
    "contact",
    "faq",
  ]),
  variant: z.string(),
  content: z.record(z.string(), z.unknown()),
});
export type GeneratedSection = z.infer<typeof GeneratedSectionSchema>;

/** The full AI generation payload. */
export const AIGenerationSchema = z.object({
  theme: ThemeSchema,
  sections: z.array(GeneratedSectionSchema).min(1),
  sampleProducts: z
    .array(
      z.object({
        name: z.string(),
        description: z.string(),
        price: z.number(),
      })
    )
    .min(1),
});
export type AIGeneration = z.infer<typeof AIGenerationSchema>;

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

export function isValidVariant(type: SectionKind, variant: string): boolean {
  const def = SECTION_DEFINITIONS[type];
  return def ? (def.variants as readonly string[]).includes(variant) : false;
}

/**
 * Validate + normalize a generated section against its content schema.
 * Returns the section with a validated `content` object, or null if invalid.
 */
export function validateSectionContent(
  type: SectionKind,
  variant: string,
  content: Record<string, unknown>
): { variant: string; content: unknown } | null {
  const def = SECTION_DEFINITIONS[type];
  if (!def) return null;
  const parsed = def.content.safeParse(content);
  if (!parsed.success) return null;
  return { variant, content: parsed.data };
}
