#!/usr/bin/env bash
# =============================================================================
# SingaPay static-IP proxy — one-shot setup (Caddy, auto-TLS via sslip.io)
#
# Why: Cloudflare Workers have no static egress IP AND cannot fetch raw IPs —
# the proxy URL must be a hostname. sslip.io maps <IP>.sslip.io → <IP> for
# free, so Caddy can auto-issue a real Let's Encrypt cert for it. No domain
# ownership needed. SingaPay sees the VPS's static IP.
#
# Usage (run as root on the VPS):
#   sudo bash singapay-proxy-setup.sh [VPS_IP] [--http] [--email ops@example.com]
#   VPS_IP: your VPS public IP (auto-detected if omitted)
#   --http: skip TLS (plain HTTP — SANDBOX ONLY, not for production)
#
# Outputs at the end: PROXY_URL + PROXY_TOKEN — give these to whoever wires
# the Cloudflare Worker (SINGAPAY_PROXY_URL / SINGAPAY_PROXY_TOKEN).
# =============================================================================
set -euo pipefail

IP="${1:-}"
[[ -z "$IP" ]] && IP="$(curl -s -4 --max-time 10 ifconfig.me || true)"
[[ -z "$IP" ]] && { echo "❌ Cannot auto-detect the VPS IP — pass it as arg 1."; exit 1; }

TLS=1
for arg in "$@"; do [[ "$arg" == "--http" ]] && TLS=0; done
EMAIL=""
for arg in "$@"; do [[ "$arg" == --email=* ]] && EMAIL="${arg#--email=}"; done
TOKEN_ARG=""
for arg in "$@"; do [[ "$arg" == --token=* ]] && TOKEN_ARG="${arg#--token=}"; done

# Token policy: --token= wins; else reuse the token already in the Caddyfile
# (re-running must NOT silently rotate the token and break the Worker var);
# else generate a fresh one. Always validated as 64 hex chars.
TOKEN=""
if [[ -n "$TOKEN_ARG" ]]; then
  TOKEN="$TOKEN_ARG"
elif [[ -f /etc/caddy/Caddyfile ]] && grep -q 'X-Proxy-Token "' /etc/caddy/Caddyfile 2>/dev/null; then
  TOKEN="$(grep -o 'X-Proxy-Token "[^"]*"' /etc/caddy/Caddyfile | head -1 | sed 's/X-Proxy-Token "//;s/"$//')"
  echo "==> Reusing existing proxy token from /etc/caddy/Caddyfile (no rotation)"
fi
[[ -z "$TOKEN" ]] && TOKEN="$(openssl rand -hex 32)"
if [[ ${#TOKEN} -ne 64 ]]; then
  echo "❌ Token must be 64 hex chars (got ${#TOKEN}). Pass a valid --token= or clear /etc/caddy/Caddyfile."
  exit 1
fi

HOSTNAME="${IP}.sslip.io"
UPSTREAM="https://sandbox-payment-b2b.singapay.id"

echo "==> SingaPay static-IP proxy setup"
echo "    VPS IP:      $IP"
echo "    Hostname:    $HOSTNAME  (sslip.io → resolves to $IP)"
echo "    TLS:         $([ $TLS = 1 ] && echo 'yes — Let'\''s Encrypt via Caddy' || echo 'NO — plain HTTP (sandbox only)')"
echo "    Proxy token: $TOKEN"
echo ""

# --- 1. install Caddy (official package repo) ---
if ! command -v caddy >/dev/null 2>&1; then
  echo "==> Installing Caddy..."
  apt-get update -qq
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  apt-get update -qq
  apt-get install -y -qq caddy
fi

# --- 2. write the Caddyfile ---
SCHEME="https"; LISTEN=""
if [ $TLS = 1 ]; then
  LISTEN="https://${HOSTNAME}"
else
  LISTEN="http://${HOSTNAME}"
fi
EMAIL_BLOCK=""
if [[ -n "$EMAIL" ]]; then
  # Caddy ≥2.9/2.11 requires global options inside a { } block, not a bare
  # "email ..." line — a flat directive breaks the parser on recent versions.
  EMAIL_BLOCK="{
	email ${EMAIL}
}"
fi

cat > /etc/caddy/Caddyfile <<EOF
# SingaPay static-IP proxy — generated by singapay-proxy-setup.sh
${EMAIL_BLOCK}

${LISTEN} {
	# Shared-secret guard: only requests with the matching token are forwarded.
	@authed header X-Proxy-Token "${TOKEN}"
	# Strip the /singapay prefix so SingaPay receives /api/v1.0/... — use
	# handle + uri strip_prefix (handle_path rejects named matchers, so the
	# token guard can't ride on it — that would open a public proxy).
	handle @authed {
		uri strip_prefix /singapay
		reverse_proxy ${UPSTREAM} {
			header_up Host sandbox-payment-b2b.singapay.id
		}
	}
	respond 403
}
EOF

# --- 3. firewall (SSH + 80/443) ---
if command -v ufw >/dev/null 2>&1; then
  echo "==> Opening firewall (OpenSSH, 80, 443)..."
  ufw allow OpenSSH >/dev/null 2>&1 || true
  ufw allow 80/tcp >/dev/null 2>&1 || true
  ufw allow 443/tcp >/dev/null 2>&1 || true
  ufw --force enable >/dev/null 2>&1 || true
fi

# --- 4. start Caddy (provisions + renews the Let's Encrypt cert automatically) ---
systemctl enable caddy >/dev/null 2>&1 || true
systemctl restart caddy
sleep 2

# --- 5. verify ---
echo ""
echo "==> Verifying..."
echo "    (a) without token → expect 403:"
curl -s -o /dev/null -w "        http_code=%{http_code}\n" "${SCHEME}://${HOSTNAME}/singapay/api/v1.0/payment-link-manage/payment-methods" || true
echo "    (b) with token → expect a SingaPay response (401/403/200 — NOT our 403):"
curl -s -o /dev/null -w "        http_code=%{http_code}\n" \
  -H "X-Proxy-Token: ${TOKEN}" -H "X-PARTNER-ID: test" \
  "${SCHEME}://${HOSTNAME}/singapay/api/v1.0/payment-link-manage/payment-methods" || true

echo ""
echo "============================================================"
echo " ✅ PROXY READY — hand these to the platform operator:"
echo "    SINGAPAY_PROXY_URL = ${SCHEME}://${HOSTNAME}/singapay"
echo "    SINGAPAY_PROXY_TOKEN = ${TOKEN}"
echo "============================================================"
echo ""
echo "Next: whitelist this VPS IP (${IP}) in the SingaPay merchant"
echo "dashboard / with SingaPay support (ip.whitelisted.merchant)."
